// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcTrevriCuWnwlDi7AmO5FcGgrYLbSkf8',
    appId: '1:121606503732:web:50323a4fbb703666eff961',
    messagingSenderId: '121606503732',
    projectId: 'cloudlab1-7f832',
    authDomain: 'cloudlab1-7f832.firebaseapp.com',
    databaseURL: 'https://cloudlab1-7f832-default-rtdb.firebaseio.com',
    storageBucket: 'cloudlab1-7f832.appspot.com',
    measurementId: 'G-S8DR7SK6D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5rH_7MPpZxB3LL1Rq3PuL8OuzdRqgOBM',
    appId: '1:121606503732:android:42ec448f68410b76eff961',
    messagingSenderId: '121606503732',
    projectId: 'cloudlab1-7f832',
    databaseURL: 'https://cloudlab1-7f832-default-rtdb.firebaseio.com',
    storageBucket: 'cloudlab1-7f832.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjg31gKuU1WqC_VLpm-ur9e0MIDZaTkJ8',
    appId: '1:121606503732:ios:aaffa82bd6b8db85eff961',
    messagingSenderId: '121606503732',
    projectId: 'cloudlab1-7f832',
    databaseURL: 'https://cloudlab1-7f832-default-rtdb.firebaseio.com',
    storageBucket: 'cloudlab1-7f832.appspot.com',
    iosBundleId: 'com.example.facultyLab1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjg31gKuU1WqC_VLpm-ur9e0MIDZaTkJ8',
    appId: '1:121606503732:ios:1688fe2acf4e04baeff961',
    messagingSenderId: '121606503732',
    projectId: 'cloudlab1-7f832',
    databaseURL: 'https://cloudlab1-7f832-default-rtdb.firebaseio.com',
    storageBucket: 'cloudlab1-7f832.appspot.com',
    iosBundleId: 'com.example.facultyLab1.RunnerTests',
  );
}
